import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { getServerSession } from 'next-auth'
import SessionProvider from '@/components/SessionProvider'
import NextAuthSessionProvider from '@/components/SessionProvider'

export const metadata: Metadata = {
  title: 'Connect Chain 🔗',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, }: { children: React.ReactNode }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>

      </body>
    </html>
  )
}
